const t=await(await fetch("http://127.0.0.1:9222/json/list")).json();
const ws=new WebSocket(t.find(x=>x.type==="page").webSocketDebuggerUrl);
await new Promise(r=>ws.onopen=r);let n=0;const p=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id))p.get(m.id)(m);};
const send=(method,params={})=>new Promise(r=>{const i=++n;p.set(i,r);ws.send(JSON.stringify({id:i,method,params}));});
const ev=async(e)=>{const r=await send("Runtime.evaluate",{expression:e,returnByValue:true,awaitPromise:true});return r.result?.result?.value;};
await send("Page.enable");await send("Runtime.enable");
await send("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:2,mobile:true});
await send("Page.navigate",{url:"http://localhost:5174/collection?bn=1"});
await new Promise(r=>setTimeout(r,3000));
await ev(`(()=>{window.__vib=[];window.__opened=null;
 Object.defineProperty(Navigator.prototype,'vibrate',{configurable:true,writable:true,value:(x)=>{window.__vib.push(x);return true;}});
 const _o=window.open; window.open=(u)=>{window.__opened=u; return null;};
 return 1;})()`);
const box=await ev(`(()=>{const el=[...document.querySelectorAll('button')].find(b=>b.innerText.trim().toUpperCase()==='BUY NOW');
 if(!el)return null; el.scrollIntoView({block:'center'}); const r=el.getBoundingClientRect();
 return JSON.stringify({x:r.x+r.width/2,y:r.y+r.height/2});})()`);
await new Promise(r=>setTimeout(r,500));
const b=JSON.parse(box);
await send("Input.dispatchMouseEvent",{type:"mousePressed",x:b.x,y:b.y,button:"left",clickCount:1});
await send("Input.dispatchMouseEvent",{type:"mouseReleased",x:b.x,y:b.y,button:"left",clickCount:1});
await new Promise(r=>setTimeout(r,1000));
console.log("vibrate:", await ev("JSON.stringify(window.__vib)"));
console.log("wa url:", await ev("window.__opened"));
ws.close();
